/* Viberr mock data — plain JS global. */
(function () {
  // Workflow stages for project "Viberr Core"
  const STAGES = [
    { id: "triage",  name: "Triage",         color: "#a5a8b5" },
    { id: "ready",   name: "Ready",          color: "#187574" },
    { id: "impl",    name: "In Progress",    color: "#7b61ff" },
    { id: "review",  name: "Review",         color: "#5b76fe" },
    { id: "done",    name: "Done",           color: "#00b473" },
  ];

  // Shorthand builders
  const codex = (role) => ({ kind: "agent", backend: "codex", name: "Codex", role });
  const claude = (role) => ({ kind: "agent", backend: "claude", name: "Claude Code", role });
  const human = (name, initials, tone) => ({ kind: "human", name, initials, tone });

  const ARDA = human("Arda Kaya", "AK", "");
  const ELIF = human("Elif Demir", "ED", "rose");
  const MURAT = human("Murat Yıldız", "MY", "teal");
  const SELIN = human("Selin Aksoy", "SA", "violet");
  // Registered in the app but not a member of this project — may comment, nothing else.
  const DENIZ = { ...human("Deniz Şahin", "DŞ", ""), guest: true };

  const TASKS = [
    {
      key: "VIB-142",
      title: "Attach execution workspace to task runtime",
      stage: "review",
      goal: "Let the operator attach a single GitHub repo to a task, create the task-key branch, and reflect branch + PR state back into the canonical task file without treating GitHub as the source of truth.",
      readiness: "input",
      specialist: codex("Developer"),
      owner: ARDA,
      operator: { name: "Operator", since: "stage 1" },
      consultants: [claude("Reviewer")],
      waiting: "human",
      urgent: true,
      validation: "changed",
      branch: "vib-142-attach-workspace",
      repo: "akin-ozer/viberr",
      pr: { number: 318, state: "review", title: "Attach execution workspace" },
      commits: [
        { sha: "a91f7c2", msg: "[VIB-142] add repo attach policy gate" },
        { sha: "4ce0b18", msg: "[VIB-142] branch reconciler + task projection" },
        { sha: "12dd9af", msg: "[VIB-142] tests for PR sync boundary" },
      ],
      changed: { files: 9, add: 412, del: 87 },
      packet: {
        type: "input",
        kind: "Completion report",
        from: "Operator",
        title: "Accept completion, or send back for one fix?",
        body: "The developer specialist reports the workspace attach flow is implemented and the review PR is open. All requested files changed and validation evidence is attached — but the PAT used in the run is missing `pull_request:write`, so PR status can't auto-sync after merge. Completion still requires explicit human acceptance.",
        observations: [
          { k: "Changed", v: "9 files · +412 / −87", code: true },
          { k: "Validation", v: "unit + integration green; 1 snapshot updated", code: false },
          { k: "Branch", v: "vib-142-attach-workspace · synced", code: true },
          { k: "Flag", v: "PAT scope missing pull_request:write", code: false },
        ],
        options: [
          { t: "Accept completion", d: "Mark task done and merge the review PR. Human-authorized.", rec: true, accept: true },
          { t: "Request one edit", d: "Ask the developer to widen PAT scope before acceptance.", rec: false, ev: "**Decision:** request one edit. Developer widens the PAT scope, then the completion report returns for acceptance." },
          { t: "Block on policy", d: "Hold until Elif updates the project credential policy.", rec: false },
        ],
      },
      timeline: [
        { type: "comment", actor: ARDA, t: "9:58", text: "@operator if the PAT scope is the only blocker, let's widen it rather than block the whole task." , to: "agent"},
        { type: "completion", actor: codex("Developer"), t: "9:41", title: "Completion report",
          text: "Implemented repo attach, branch creation, and PR-sync projection. Validation green except one snapshot intentionally updated.",
          evidence: [
            { label: "unit/policy_gate_test", add: "+14", del: "0" },
            { label: "integration/pr_sync_test", add: "+38", del: "−4" },
          ] },
        { type: "github", actor: codex("Developer"), t: "9:39", text: "Opened **PR #318** from `vib-142-attach-workspace` into `main`." },
        { type: "policy", actor: { name: "Policy engine", kind: "system" }, t: "9:38", text: "**Policy violation:** active PAT is missing `pull_request:write`. Auto-sync after merge will fail." },
        { type: "quality", actor: claude("Reviewer"), t: "9:20", text: "**Quality flag:** snapshot `task_projection.json` changed — confirm the new compact shape is intended before review." },
        { type: "transition", actor: { name: "Operator", kind: "agent" }, t: "9:02", text: "**Transition request:** move VIB-142 from In Progress to Review. Branch healthy, evidence attached." },
        { type: "agent", actor: { name: "Operator", kind: "agent" }, t: "8:30", text: "Re-engaged **Claude Code (Reviewer)** as consultant; re-anchored on `task.md` before review." },
        { type: "comment", actor: codex("Developer"), t: "8:12", text: "Branch work complete. Handing back to operator for the review boundary." },
        { type: "assign", actor: ARDA, day: "Yesterday", t: "15:12", text: "Took task ownership — owner is the human reviewer and acceptance authority for this task." },
      ],
    },
    {
      key: "VIB-148",
      title: "Validate PAT scope before GitHub sync",
      stage: "ready",
      goal: "Pre-flight the project's GitHub credential against required scopes and surface a typed policy event if anything is missing, before any branch is created.",
      readiness: "input",
      specialist: null,
      owner: null,
      operator: { name: "Operator", since: "stage 1" },
      consultants: [],
      waiting: "human",
      urgent: false,
      validation: "none",
      branch: null,
      repo: "akin-ozer/viberr",
      pr: null,
      timeline: [
        { type: "agent", actor: { name: "Operator", kind: "agent" }, t: "8:36", text: "**Quality gate:** goal and scope are executable. Waiting on a human owner for the acceptance boundary before execution is scheduled." },
        { type: "comment", actor: ELIF, t: "8:20", text: "Scoped the pre-flight checks. Needs an owner on the acceptance gate before any branch is created." },
      ],
    },
    {
      key: "VIB-151",
      title: "Compress long-running task timelines",
      stage: "impl",
      goal: "Apply the compression threshold so long task histories stay readable: collapse routine chatter, keep typed important events, preserve continuity for re-anchoring.",
      readiness: "ready",
      specialist: claude("Developer"),
      owner: SELIN,
      operator: { name: "Operator", since: "stage 2" },
      consultants: [codex("Consultant")],
      waiting: "agent",
      urgent: false,
      validation: "healthy",
      branch: "vib-151-timeline-compression",
      repo: "akin-ozer/viberr",
      pr: null,
      timeline: [
        { type: "comment", actor: claude("Developer"), t: "10:24", text: "Threshold sweep running against the 40-event fixture. Typed events survive every compression pass so far." },
        { type: "agent", actor: { name: "Operator", kind: "agent" }, t: "9:47", text: "Re-anchored **Codex (Consultant)** on `task.md` for a second opinion on threshold defaults." },
        { type: "github", actor: claude("Developer"), t: "9:31", text: "Pushed 2 commits to `vib-151-timeline-compression` — compaction map and threshold config." },
        { type: "assign", actor: SELIN, day: "Yesterday", t: "14:20", text: "Took task ownership ahead of the review boundary." },
        { type: "agent", actor: { name: "Operator", kind: "agent" }, day: "Yesterday", t: "14:05", text: "Assigned **Claude Code (Developer)** as primary specialist — branch `vib-151-timeline-compression` created." },
      ],
    },
    {
      key: "VIB-153",
      title: "Operator brevity guardrail for packets",
      stage: "impl",
      goal: "Constrain operator packets to observed → changed → recommended → decision, rejecting verbose or duplicated summaries.",
      readiness: "ready",
      specialist: codex("Developer"),
      owner: null,
      operator: { name: "Operator", since: "stage 2" },
      consultants: [],
      waiting: "agent",
      urgent: false,
      validation: "healthy",
      branch: "vib-153-operator-brevity",
      repo: "akin-ozer/viberr",
      pr: null,
      timeline: [
        { type: "comment", actor: DENIZ, t: "10:12", text: "Following from the platform team — this packet budget will matter for our ops rollout too." },
        { type: "comment", actor: codex("Developer"), t: "10:02", text: "Brevity linter drafted — packets past the length budget bounce back to the operator with a diff of what to cut." },
        { type: "agent", actor: { name: "Operator", kind: "agent" }, t: "8:58", text: "Assigned **Codex (Developer)** as primary specialist — branch `vib-153-operator-brevity` created." },
      ],
    },
    {
      key: "VIB-160",
      title: "Rehydrate specialist from canonical file",
      stage: "impl",
      goal: "When provider-side runtime history is unavailable, continue specialist work from the canonical task file and record a continuity warning instead of failing.",
      readiness: "input",
      specialist: claude("Developer"),
      owner: MURAT,
      operator: { name: "Operator", since: "stage 3" },
      consultants: [codex("Consultant")],
      waiting: "human",
      urgent: false,
      validation: "failing",
      branch: "vib-160-rehydrate",
      repo: "akin-ozer/viberr",
      pr: null,
      packet: {
        type: "blocked",
        kind: "Blocked decision",
        from: "Operator",
        title: "Continuity degraded — pick a recovery path",
        body: "Provider-side history for the Developer thread is unavailable. The specialist was rehydrated from the canonical task file and can continue safely, but two rehydrate-path checks are failing and the earlier direction may be stale.",
        observations: [
          { k: "Observed", v: "provider session 404 · thread claude-dev-160", code: true },
          { k: "Changed", v: "specialist rehydrated from task.md · continuity warning recorded", code: false },
          { k: "Validation", v: "2 rehydrate-path checks failing", code: false },
          { k: "Branch", v: "vib-160-rehydrate · 2 commits behind main", code: true },
        ],
        options: [
          { t: "Resume rehydrated thread", d: "Continue from canonical state; re-run the failing checks before any new commits.", rec: true, ev: "**Decision:** resume the rehydrated thread. Operator re-anchors Claude Code (Developer) on `task.md` and re-runs the failing checks before new commits." },
          { t: "Start a fresh specialist", d: "Retire the degraded thread; a new Developer anchors on task.md.", rec: false, ev: "**Decision:** start a fresh specialist. The degraded thread is retired and a new Developer thread anchors on the canonical file." },
          { t: "Hold for runtime debug", d: "Keep the task blocked while the provider-native session is inspected.", rec: false },
        ],
      },
      timeline: [
        { type: "blocked", actor: { name: "Operator", kind: "agent" }, t: "10:31", text: "**Blocked decision:** provider history unavailable and two rehydrate checks failing — recovery packet raised for human review." },
        { type: "quality", actor: codex("Consultant"), t: "10:18", text: "**Quality flag:** the rehydrate path drops evidence references recorded before the continuity break." },
        { type: "agent", actor: { name: "Operator", kind: "agent" }, t: "10:05", text: "**Continuity warning:** runtime history unavailable — re-anchored **Claude Code (Developer)** on the canonical task file." },
        { type: "github", actor: claude("Developer"), t: "9:52", text: "Pushed `vib-160-rehydrate` — recovery shim and continuity marker." },
        { type: "quality", actor: codex("Consultant"), day: "Yesterday", t: "12:10", text: "**Validation failing** on the rehydrate path — evidence attached, re-run requested." },
        { type: "comment", actor: MURAT, day: "Yesterday", t: "11:20", text: "Opened the Developer runtime session to debug continuity — session recorded per audit policy." },
      ],
    },
    {
      key: "VIB-145",
      title: "Board card SSE revalidation",
      stage: "review",
      goal: "Push task-state changes to all connected users within 5 seconds using server-sent events and route-local revalidation.",
      readiness: "ready",
      specialist: codex("Developer"),
      owner: null,
      operator: { name: "Operator", since: "stage 2" },
      consultants: [],
      waiting: "agent",
      urgent: false,
      validation: "healthy",
      branch: "vib-145-sse-revalidate",
      repo: "akin-ozer/viberr",
      pr: { number: 311, state: "review", title: "SSE board revalidation" },
      timeline: [
        { type: "transition", actor: { name: "Operator", kind: "agent" }, t: "9:12", text: "**Transition request:** move VIB-145 from In Progress to Review — SSE fan-out demo recorded, evidence attached." },
        { type: "comment", actor: codex("Developer"), t: "8:51", text: "Review build is green across the three desktop browser targets. Reviewer thread can start on the diff." },
        { type: "github", actor: codex("Developer"), day: "Yesterday", t: "16:40", text: "Opened **PR #311** from `vib-145-sse-revalidate` into `main`." },
      ],
    },
    {
      key: "VIB-139",
      title: "Separate human RBAC from agent capability policy",
      stage: "done",
      goal: "Model human roles and agent capabilities as two distinct policy surfaces so managing people and managing agents never collide.",
      readiness: "done",
      specialist: null,
      owner: ELIF,
      operator: { name: "Operator", since: "stage 1" },
      consultants: [],
      waiting: "none",
      validation: "healthy",
      branch: "vib-139-policy-split",
      repo: "akin-ozer/viberr",
      pr: { number: 298, state: "merged", title: "Policy split" },
      timeline: [
        { type: "completion", actor: ELIF, day: "Mar 30", t: "17:26", title: "Completion accepted", text: "Human acceptance recorded — **PR #298** merged. Human RBAC and agent capability are now separate policy surfaces." },
        { type: "transition", actor: { name: "Operator", kind: "agent" }, day: "Mar 30", t: "17:10", text: "**Transition request:** move VIB-139 from Review to Done — both policy surfaces validated." },
      ],
    },
    {
      key: "VIB-141",
      title: "Typed important-event schema",
      stage: "done",
      goal: "Define the five typed events — quality flag, transition request, blocked decision, completion report, policy violation — as first-class records.",
      readiness: "done",
      specialist: codex("Developer"),
      owner: MURAT,
      operator: { name: "Operator", since: "stage 1" },
      consultants: [],
      waiting: "none",
      validation: "healthy",
      branch: "vib-141-typed-events",
      repo: "akin-ozer/viberr",
      pr: { number: 287, state: "merged", title: "Typed events" },
      timeline: [
        { type: "github", actor: MURAT, day: "Mar 30", t: "15:02", text: "Merged **PR #287** — the typed important-event schema is live." },
        { type: "quality", actor: claude("Reviewer"), day: "Mar 30", t: "14:31", text: "**Quality flag resolved:** typed payloads carry actor identity and task references." },
      ],
    },
    {
      key: "VIB-166",
      title: "Manual re-scan & state reconciliation",
      stage: "triage",
      goal: "Give users a manual re-scan action that reconciles the file-native store when automated change detection misses a directly-edited task file.",
      readiness: "input",
      specialist: null,
      owner: null,
      operator: null,
      consultants: [],
      waiting: "human",
      urgent: false,
      validation: "none",
      branch: null,
      repo: "akin-ozer/viberr",
      pr: null,
      timeline: [],
    },
    {
      key: "VIB-168",
      title: "Agent profile templates (eligible stages)",
      stage: "triage",
      goal: "Reusable agent profiles defining eligible stages, permitted actions, context resources, and backend — global base with per-project overrides.",
      readiness: "input",
      specialist: null,
      owner: null,
      operator: null,
      consultants: [],
      waiting: "human",
      urgent: false,
      validation: "none",
      branch: null,
      repo: "akin-ozer/viberr",
      pr: null,
      timeline: [],
    },
  ];

  // Agent runtime — live + historical SDK streams per task (operator / primary / consultants).
  // Line shapes mirror the real wire formats:
  //  · Claude Code: claude -p --output-format stream-json  →  NDJSON of system·init /
  //    assistant (text, tool_use) / user (tool_result) / result envelopes with session_id.
  //  · Codex SDK: thread.runStreamed()  →  JSONL ThreadEvents: thread.started, turn.started,
  //    item.started/item.completed (command_execution, agent_message, file_change, reasoning),
  //    turn.completed with token usage.
  const cc = { // Claude Agent SDK / stream-json
    init: (t, s) => ({ t, ev: "init", tag: "system·init", text: s }),
    text: (t, s) => ({ t, ev: "text", tag: "assistant", text: s }),
    tool: (t, n, s, input) => ({ t, ev: "tool", tag: "tool_use", name: n, text: s, input: input || null }),
    out:  (t, s) => ({ t, ev: "out", tag: "tool_result", text: s }),
    err:  (t, s) => ({ t, ev: "err", tag: "tool_result", text: s, isError: true }),
    res:  (t, s, stats) => ({ t, ev: "result", tag: "result", text: s, stats: stats || null }),
  };
  const cx = { // Codex SDK runStreamed() ThreadEvents
    start: (t, s) => ({ t, ev: "init", tag: "thread.started", text: s }),
    turn:  (t, s) => ({ t, ev: "meta", tag: "turn.started", text: s }),
    think: (t, s) => ({ t, ev: "think", tag: "reasoning", text: s }),
    exec:  (t, s) => ({ t, ev: "tool", tag: "command_execution", name: "exec", text: s }),
    out:   (t, s, exit) => ({ t, ev: exit ? "err" : "out", tag: "aggregated_output", text: s, exit: exit || 0 }),
    msg:   (t, s) => ({ t, ev: "text", tag: "agent_message", text: s }),
    diff:  (t, s, changes) => ({ t, ev: "diff", tag: "file_change", text: s, changes: changes || null }),
    done:  (t, s, usage) => ({ t, ev: "result", tag: "turn.completed", text: s, usage: usage || null }),
  };
  const OP = { kind: "agent", name: "Operator" };

  const RUNTIME = {
    "VIB-142": [
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "e4b8a1c2-0142-4d6f-9a3b-7c5e8f01d442",
        state: "idle", phase: "Waiting on human acceptance", turns: 11, tokens: 18700,
        lines: [
          cc.init("08:02:11", "session e4b8a1c2 · claude-sonnet-4-5 · 9 tools · mcp: viberr-task-store · cwd /work/viberr"),
          cc.text("09:02:20", "Transition request raised: In Progress → Review, evidence attached."),
          cc.text("09:41:12", "Completion report received from the Developer. Packet raised for human acceptance."),
          cc.text("09:58:30", "Arda's guidance noted — PAT-scope preference recorded against the open decision."),
        ] },
      { id: "primary", role: "Primary specialist", who: codex("Developer"), backend: "codex", sdk: "Codex SDK", model: "gpt-5.4-codex", sid: "0199a1f3-4c02-7d31-8b6e-2f41aa90c4d7",
        state: "done", finished: "9:41", turns: 9, tokens: 128400,
        lines: [
          cx.start("08:12:04", "thread 0199a1f3-4c02… resumed · gpt-5.4-codex"),
          cx.turn("08:12:05", "turn 9"),
          cx.exec("08:12:31", "npm test -- --filter=pr-sync"),
          cx.out("08:13:02", "integration/pr_sync: 38 passed · 0 failed"),
          cx.diff("09:12:40", "9 files · +412 −87 · policy gate, branch reconciler, task projection", [
            { path: "src/github/policy_gate.ts", kind: "update" },
            { path: "src/github/reconciler.ts", kind: "add" },
            { path: "src/task/projection.ts", kind: "update" },
          ]),
          cx.exec("09:39:12", "gh pr create --title 'Attach execution workspace' --base main"),
          cx.out("09:39:15", "PR #318 created · vib-142-attach-workspace → main"),
          cx.msg("09:40:58", "Completion report drafted with validation evidence — handing back to the operator."),
          cx.done("09:41:02", "turn 9 · in 128k (cached 96k) · out 6.2k tokens · 92m", { input_tokens: 128034, cached_input_tokens: 96410, output_tokens: 6188 }),
        ] },
      { id: "c0", role: "Consultant", who: claude("Reviewer"), backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "a91f7c2e-8b4d-4e0a-b6c1-3d5f9e214298",
        state: "done", finished: "9:20", turns: 4, tokens: 41200,
        lines: [
          cc.init("08:30:02", "session a91f7c2e resumed · claude-sonnet-4-5 · re-anchored on task.md"),
          cc.tool("08:31:10", "Bash", "gh pr diff 318 --stat"),
          cc.out("08:31:14", "9 files changed, 412 insertions(+), 87 deletions(-)"),
          cc.tool("09:18:40", "Bash", "npm run snapshot:verify"),
          cc.err("09:19:02", "task_projection.json changed — compact shape not confirmed"),
          cc.text("09:20:11", "Raising a quality flag: confirm the new compact shape is intended before review."),
          cc.res("09:20:15", "success · 4 turns · 2m 12s api · $0.31", { dur: 132400, api: 98120, turns: 4, cost: 0.31, in: 812, cached: 38210, out: 2140 }),
        ] },
    ],
    "VIB-151": [
      { id: "primary", role: "Primary specialist", who: claude("Developer"), backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "51d8f0e2-3a7b-4c1b-9e0a-6f4d2b8c7151",
        state: "running", phase: "Running validation sweep", step: "Bash · npm test -- --filter=long-fixture", started: "10:18", elapsed: 402, turns: 14, tokens: 38400,
        lines: [
          cc.init("10:18:02", "session 51d8f0e2 · claude-sonnet-4-5 · 9 tools · mcp: github, filesystem · cwd /work/viberr"),
          cc.text("10:18:09", "Re-anchoring on the canonical task file before continuing stage work."),
          cc.tool("10:18:11", "Read", ".viberr/tasks/VIB-151/task.md", { file_path: ".viberr/tasks/VIB-151/task.md" }),
          cc.out("10:18:12", "412 lines · anchor ok · last typed event: consultant re-engaged 9:47"),
          cc.tool("10:18:20", "Grep", "COMPRESS_THRESHOLD src/", { pattern: "COMPRESS_THRESHOLD", path: "src/" }),
          cc.out("10:18:21", "3 matches · timeline/compress.ts:41,88 · config/defaults.ts:12"),
          cc.tool("10:18:44", "Edit", "timeline/compress.ts — always keep typed events above threshold", { file_path: "src/timeline/compress.ts" }),
          cc.out("10:18:45", "ok · +18 −6"),
          cc.tool("10:19:03", "Bash", "npm test -- --filter=compression"),
          cc.out("10:19:31", "40-event fixture: 12 passed · snapshot compaction_map updated"),
          cc.text("10:19:40", "Typed events survive every pass. Running the long-fixture sweep next."),
          cc.tool("10:19:46", "Bash", "npm test -- --filter=long-fixture"),
        ],
        live: [
          cc.out("10:24:12", "400-event fixture: compaction 6.2:1 · continuity anchors kept"),
          cc.text("10:24:20", "Threshold 40 holds. Checking the re-anchor read path against compressed history."),
          cc.tool("10:24:24", "Read", "timeline/reanchor.ts", { file_path: "src/timeline/reanchor.ts" }),
          cc.out("10:24:25", "202 lines"),
          cc.tool("10:24:58", "Edit", "timeline/reanchor.ts — read compressed spans lazily", { file_path: "src/timeline/reanchor.ts" }),
          cc.out("10:24:59", "ok · +9 −2"),
          cc.tool("10:25:07", "Bash", "npm test -- --filter=reanchor"),
          cc.out("10:25:19", "8 passed · 0 failed (4.1s)"),
          cc.text("10:25:26", "Green. Committing the compaction map and lazy reads."),
          cc.tool("10:25:31", "Bash", "git commit -m '[VIB-151] compaction map + lazy compressed reads'"),
          cc.out("10:25:33", "2 files changed · +27 −8 · vib-151-timeline-compression"),
        ] },
      { id: "c0", role: "Consultant", who: codex("Consultant"), backend: "codex", sdk: "Codex SDK", model: "gpt-5.4-codex", sid: "0199a2c4-7b31-7802-9f4e-51cb22ee8f21",
        state: "running", phase: "Advisory pass on threshold defaults", step: "exec · rg 'compression-threshold' .viberr/policy/", started: "10:29", elapsed: 74, turns: 3, tokens: 51200,
        lines: [
          cx.start("10:29:41", "thread 0199a2c4-7b31… resumed · gpt-5.4-codex"),
          cx.turn("10:29:42", "turn 3"),
          cx.think("10:29:48", "Compare threshold defaults against long-task readability before advising."),
          cx.exec("10:29:55", "git diff main...vib-151-timeline-compression --stat"),
          cx.out("10:29:57", "7 files changed · +214 −41"),
        ],
        live: [
          cx.exec("10:30:14", "rg 'compression-threshold' .viberr/policy/"),
          cx.out("10:30:15", "guardrails.yml:12 · value: 40 · typed events always kept"),
          cx.think("10:30:24", "Policy already owns the value — the constant in defaults.ts should defer to it."),
          cx.msg("10:30:33", "Recommend reading the threshold from project guardrails with 40 as fallback. Posting advisory to the task timeline."),
          cx.done("10:30:36", "turn 3 · in 51.2k (cached 38.9k) · out 1.9k tokens", { input_tokens: 51234, cached_input_tokens: 38912, output_tokens: 1954 }),
          cx.turn("10:30:41", "turn 4"),
          cx.exec("10:30:49", "rg 'COMPRESS_THRESHOLD' src/config/"),
          cx.out("10:30:50", "defaults.ts:12 · fallback candidate confirmed"),
        ] },
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "b7e2c9a4-1151-4f8d-a0b3-5c6d7e8f9151",
        state: "idle", phase: "Supervising — next boundary: Review", turns: 6, tokens: 12100,
        lines: [
          cc.init("09:47:00", "session b7e2c9a4 · operator runtime · anchored .viberr/tasks/VIB-151/task.md"),
          cc.text("09:47:05", "Re-engaged the Codex consultant for a second opinion on threshold defaults."),
          cc.text("10:18:00", "Primary specialist resumed for the validation sweep. Watching for the review boundary."),
        ] },
    ],
    "VIB-153": [
      { id: "primary", role: "Primary specialist", who: codex("Developer"), backend: "codex", sdk: "Codex SDK", model: "gpt-5.4-codex", sid: "0199a0b8-53c9-7f10-a2d4-8e7b3c150953",
        state: "running", phase: "Implementing brevity guardrail", step: "exec · npm test -- --filter=brevity", started: "8:58", elapsed: 5462, turns: 6, tokens: 96300,
        lines: [
          cx.start("08:58:31", "thread 0199a0b8-53c9… started · gpt-5.4-codex"),
          cx.turn("08:58:32", "turn 1"),
          cx.think("08:58:40", "Draft a linter that enforces the packet length budget with a bounce-back diff."),
          cx.exec("08:59:02", "rg 'packet' src/operator/ --files-with-matches"),
          cx.out("08:59:03", "4 files · authoring.ts, budget.ts, packet.ts, verbosity.ts"),
          cx.diff("09:58:12", "src/operator/brevity.ts (+64) · budget wired to observed → changed → recommended → decision", [
            { path: "src/operator/brevity.ts", kind: "add" },
          ]),
          cx.msg("10:02:19", "Linter drafted — over-budget packets bounce back with a diff of what to cut."),
        ],
        live: [
          cx.turn("10:26:02", "turn 6"),
          cx.exec("10:26:11", "npm test -- --filter=brevity"),
          cx.out("10:26:29", "6 passed · 0 failed (3.2s)"),
          cx.think("10:26:40", "Wire the reject path into packet authoring so violations never reach the timeline."),
          cx.exec("10:27:04", "git commit -m '[VIB-153] brevity linter + bounce-back diff'"),
          cx.out("10:27:06", "2 files changed · +71 −3 · vib-153-operator-brevity"),
          cx.msg("10:27:18", "Reject path wired. Starting duplicate-summary detection next."),
        ] },
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "c8f3d0b5-2153-4a9e-b1c4-6d7e8f0a1153",
        state: "idle", phase: "Supervising — validation healthy", turns: 3, tokens: 6400,
        lines: [
          cc.init("08:58:12", "session c8f3d0b5 · operator runtime · anchored .viberr/tasks/VIB-153/task.md"),
          cc.text("08:58:20", "Assigned Codex as primary specialist — branch vib-153-operator-brevity created."),
        ] },
    ],
    "VIB-160": [
      { id: "primary", role: "Primary specialist", who: claude("Developer"), backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "d9a4e1c6-3160-4b0f-92d5-7e8f9a0b2160",
        state: "error", finished: "10:31", turns: 5, tokens: 22800,
        lines: [
          cc.init("10:04:41", "resume claude-dev-160 — provider session lookup"),
          cc.err("10:04:44", "provider session 404 · runtime history unavailable"),
          cc.init("10:05:02", "rehydrated from .viberr/tasks/VIB-160/task.md · continuity warning recorded"),
          cc.text("10:05:20", "Continuing from canonical state — earlier direction may be stale, verifying."),
          cc.tool("10:09:33", "Bash", "npm test -- --filter=rehydrate"),
          cc.err("10:10:04", "2 failed · evidence refs dropped before the continuity break"),
          cc.res("10:31:00", "halted · operator raised a blocked decision packet", { subtype: "error_during_execution", dur: 1579000, api: 402000, turns: 5, cost: 0.87, in: 1424, cached: 51200, out: 3810 }),
        ] },
      { id: "c0", role: "Consultant", who: codex("Consultant"), backend: "codex", sdk: "Codex SDK", model: "gpt-5.4-codex", sid: "0199a29d-60aa-7433-b1c8-4d92e07f6a60",
        state: "done", finished: "10:18", turns: 2, tokens: 22400,
        lines: [
          cx.start("10:12:20", "thread 0199a29d-60aa… resumed · gpt-5.4-codex"),
          cx.exec("10:15:40", "git log --oneline vib-160-rehydrate ^main"),
          cx.out("10:15:41", "2 commits · recovery shim, continuity marker"),
          cx.msg("10:18:09", "Quality flag: the rehydrate path drops evidence references recorded before the break."),
          cx.done("10:18:12", "turn 2 · in 22.4k (cached 18.2k) · out 0.8k tokens", { input_tokens: 22391, cached_input_tokens: 18240, output_tokens: 812 }),
        ] },
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "e0b5f2d7-4160-4c1a-83e6-8f9a0b1c3160",
        state: "idle", phase: "Blocked — waiting on human decision", turns: 7, tokens: 15600,
        lines: [
          cc.init("10:05:00", "session e0b5f2d7 · operator runtime · anchored .viberr/tasks/VIB-160/task.md"),
          cc.text("10:05:08", "Continuity warning recorded — specialist re-anchored on the canonical file."),
          cc.text("10:31:02", "Blocked decision packet raised — waiting on a human recovery path."),
        ] },
    ],
    "VIB-145": [
      { id: "primary", role: "Primary specialist", who: codex("Developer"), backend: "codex", sdk: "Codex SDK", model: "gpt-5.4-codex", sid: "0199a145-9e77-7b05-8c3a-6f2d81b4e145",
        state: "running", phase: "Standing by on review thread", step: "exec · rg 'revalidate' src/board/ -n", started: "9:14", elapsed: 4820, turns: 12, tokens: 88200,
        lines: [
          cx.start("09:14:02", "thread 0199a145-9e77… resumed · gpt-5.4-codex"),
          cx.turn("09:14:03", "turn 11"),
          cx.exec("09:14:30", "npm run e2e -- --browsers=chromium,firefox,webkit"),
          cx.out("09:16:22", "3/3 browser targets green · fan-out latency p95 3.8s"),
          cx.msg("09:17:04", "Review build green. Holding the thread open for reviewer questions."),
        ],
        live: [
          cx.turn("10:32:40", "turn 12"),
          cx.exec("10:32:51", "rg 'revalidate' src/board/ -n"),
          cx.out("10:32:52", "6 matches · sse.ts, cache.ts"),
          cx.msg("10:33:20", "Prefetching answers for the review thread — no new commits planned."),
        ] },
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "f1c6a3e8-5145-4d2b-94f7-9a0b1c2d4145",
        state: "idle", phase: "Transition request pending approval", turns: 5, tokens: 9800,
        lines: [
          cc.init("09:10:44", "session f1c6a3e8 · operator runtime · anchored .viberr/tasks/VIB-145/task.md"),
          cc.text("09:12:10", "Transition request raised: In Progress → Review — SSE fan-out demo recorded."),
        ] },
    ],
    "VIB-148": [
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "a2d7e4f1-0148-4b3c-85a9-1c2d3e4f5148",
        state: "idle", phase: "Waiting on a human owner", turns: 2, tokens: 3100,
        lines: [
          cc.init("08:24:30", "session a2d7e4f1 · operator runtime · anchored .viberr/tasks/VIB-148/task.md"),
          cc.tool("08:35:52", "Read", ".viberr/tasks/VIB-148/task.md", { file_path: ".viberr/tasks/VIB-148/task.md" }),
          cc.out("08:35:53", "96 lines · goal + scope present · no owner on the acceptance boundary"),
          cc.text("08:36:04", "Quality gate passed: goal and scope are executable."),
          cc.text("08:36:10", "Waiting on a human owner for the acceptance boundary before scheduling execution."),
        ] },
    ],
    "VIB-139": [
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "b3c8f5a2-0139-4c4d-96b0-2d3e4f5a6139",
        state: "done", finished: "Mar 30 · 17:26", turns: 9, tokens: 14800,
        lines: [
          cc.init("16:58:00", "session b3c8f5a2 · operator runtime · anchored .viberr/tasks/VIB-139/task.md"),
          cc.text("17:10:12", "Transition request raised: Review → Done — both policy surfaces validated."),
          cc.text("17:26:31", "Human acceptance recorded by Elif — PR #298 merged. Closing operator session."),
          cc.res("17:26:40", "success · 9 turns · session closed on completion", { dur: 2412000, api: 186000, turns: 9, cost: 0.42, in: 1120, cached: 42800, out: 2960 }),
        ] },
    ],
    "VIB-141": [
      { id: "primary", role: "Primary specialist", who: codex("Developer"), backend: "codex", sdk: "Codex SDK", model: "gpt-5.4-codex", sid: "0199a141-77e2-7c08-b5d6-9a0b1c2d3141",
        state: "done", finished: "Mar 30 · 14:52", turns: 7, tokens: 74200,
        lines: [
          cx.start("13:40:11", "thread 0199a141-77e2… started · gpt-5.4-codex"),
          cx.turn("13:40:12", "turn 7"),
          cx.exec("14:31:20", "npm test -- --filter=typed-events"),
          cx.out("14:31:44", "21 passed · 0 failed (6.8s)"),
          cx.diff("14:40:02", "src/events/schema.ts (+120) · src/events/types.ts · five typed events as first-class records", [
            { path: "src/events/schema.ts", kind: "add" },
            { path: "src/events/types.ts", kind: "update" },
          ]),
          cx.msg("14:51:38", "Typed important-event schema complete — payloads carry actor identity and task references."),
          cx.done("14:52:01", "turn 7 · in 74.2k (cached 60.1k) · out 3.4k tokens", { input_tokens: 74212, cached_input_tokens: 60110, output_tokens: 3421 }),
        ] },
      { id: "c0", role: "Consultant", who: claude("Reviewer"), backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "d5e0b7c4-1141-4e6f-b8d2-4f5a6b7c8141",
        state: "done", finished: "Mar 30 · 14:31", turns: 3, tokens: 28600,
        lines: [
          cc.init("14:12:08", "session d5e0b7c4 resumed · claude-sonnet-4-5 · re-anchored on task.md"),
          cc.tool("14:20:15", "Bash", "npm run schema:lint"),
          cc.out("14:20:19", "clean · 0 warnings"),
          cc.text("14:31:02", "Quality flag resolved — typed payloads carry actor identity and task references."),
          cc.res("14:31:10", "success · 3 turns · 1m 41s api · $0.19", { dur: 98400, api: 101000, turns: 3, cost: 0.19, in: 640, cached: 26100, out: 1480 }),
        ] },
      { id: "op", op: true, role: "Operator", who: OP, backend: "claude", sdk: "Claude Agent SDK", model: "claude-sonnet-4-5", sid: "c4d9a6b3-0141-4d5e-a7c1-3e4f5a6b7141",
        state: "done", finished: "Mar 30 · 15:02", turns: 8, tokens: 13900,
        lines: [
          cc.init("13:38:50", "session c4d9a6b3 · operator runtime · anchored .viberr/tasks/VIB-141/task.md"),
          cc.text("13:40:05", "Assigned Codex as primary specialist — branch vib-141-typed-events created."),
          cc.text("15:02:12", "Completion accepted — Murat merged PR #287. Closing operator session."),
          cc.res("15:02:20", "success · 8 turns · session closed on completion", { dur: 5010000, api: 154000, turns: 8, cost: 0.36, in: 980, cached: 38400, out: 2410 }),
        ] },
    ],
  };

  // Agent profiles — reusable capability definitions (FR8/FR9).
  const AGENTS = {
    operator: {
      id: "operator", kind: "operator", name: "Operator", role: "Task coordinator", icon: "shield",
      backends: ["claude"], model: "orchestration runtime", scope: "System role · one per active task",
      desc: "A dedicated operator is instantiated for every active task. It coordinates specialists, keeps the canonical task file authoritative, and turns agent work into concise decision packets for human review. It never writes code and never closes a task itself.",
      stages: ["triage", "ready", "impl", "review", "done"], spanAll: true,
      actions: {
        direct: ["Assign the primary specialist", "Summon consultant specialists", "Generate decision & blocking packets", "Append typed important events", "Compress long-running timelines"],
        recommend: ["Stage transitions", "Completion for human acceptance", "Owner re-assignment"],
        forbidden: ["Execute code or write to the repo", "Transition a task to Done", "Change project policy"],
      },
      resources: {
        skills: ["packet-authoring", "timeline-compression", "continuity-reanchor"],
        mcps: ["viberr-task-store"],
        kb: ["Project workflow rules", "Agent capability matrix"],
      },
    },
    profiles: [
      {
        id: "developer", kind: "specialist", name: "Developer", role: "Implementation", icon: "branch",
        backends: ["codex", "claude"], model: "codex-large · claude-sonnet", scope: "Global base · customized for Viberr Core",
        desc: "Implements stage work on the task-key branch: writes code, runs local validation, and opens the review PR. Hands back to the operator at the review boundary.",
        stages: ["ready", "impl"],
        actions: {
          direct: ["Create the task-key branch", "Commit & push to the branch", "Run unit & integration validation", "Open the review pull request"],
          recommend: ["Move the task to Review", "Report a validation verdict"],
          forbidden: ["Merge a pull request", "Transition a task to Done", "Edit another task's branch"],
        },
        resources: { skills: ["repo-write", "test-runner", "lint-autofix"], mcps: ["github", "filesystem"], kb: ["Viberr Core architecture", "Coding standards"] },
      },
      {
        id: "reviewer", kind: "specialist", name: "Reviewer", role: "Code review", icon: "check",
        backends: ["claude"], model: "claude-sonnet", scope: "Global base · customized for Viberr Core",
        desc: "Reviews the diff at the review boundary, raises typed quality flags, and recommends approve or request-changes. Re-anchors on the canonical task file before each review.",
        stages: ["review"],
        actions: {
          direct: ["Read the repository & diff", "Run validation suites", "Post quality-flag events", "Comment on the task"],
          recommend: ["Approve the review", "Request changes"],
          forbidden: ["Merge a pull request", "Transition a task to Done", "Push commits to the branch"],
        },
        resources: { skills: ["diff-review", "security-scan"], mcps: ["github"], kb: ["Review checklist", "Security guidelines"] },
      },
      {
        id: "tester", kind: "specialist", name: "Tester", role: "Validation", icon: "bolt",
        backends: ["codex"], model: "codex-large", scope: "Global base · default settings",
        desc: "Authors and runs the validation suite, attaches evidence to the task, and reports a clear pass/fail verdict — keeping raw validation output out of the timeline.",
        stages: ["impl", "review"],
        actions: {
          direct: ["Author test cases", "Run the validation suite", "Attach evidence references"],
          recommend: ["Validation verdict", "Hold the task on failing checks"],
          forbidden: ["Merge a pull request", "Transition a task to Done"],
        },
        resources: { skills: ["test-author", "coverage-report"], mcps: ["github", "filesystem"], kb: ["Test strategy"] },
      },
      {
        id: "consultant", kind: "specialist", name: "Consultant", role: "Advisory", icon: "message",
        backends: ["claude", "codex"], model: "claude-sonnet · codex-large", scope: "Global base · customized for Viberr Core",
        desc: "Persistent expert memory the operator can re-engage across stages. Reads and advises only — never writes to the repository or moves the task.",
        stages: ["triage", "ready", "impl", "review"],
        actions: {
          direct: ["Read the task & repository", "Comment with guidance"],
          recommend: ["Flag underspecified tasks"],
          forbidden: ["Write to the repository", "Open or merge a PR", "Any stage transition"],
        },
        resources: { skills: ["domain-advisor"], mcps: ["github"], kb: ["Product brief", "Domain glossary", "Prior decisions"] },
      },
    ],
  };

  // Project policy — human RBAC and agent capability, managed separately (FR2, FR6–FR9).
  const POLICY = {
    edited: { by: "Elif Demir", t: "Mar 30" },
    members: [
      { p: ELIF, role: "admin", email: "elif@viberr.dev", status: "active" },
      { p: ARDA, role: "admin", email: "arda@viberr.dev", status: "active" },
      { p: MURAT, role: "maintainer", email: "murat@viberr.dev", status: "active" },
      { p: SELIN, role: "reviewer", email: "selin@viberr.dev", status: "active" },
    ],
    rbac: [
      { action: "View board, tasks & timelines", grant: { admin: 1, maintainer: 1, reviewer: 1, viewer: 1 } },
      { action: "Comment on tasks (app-wide)", grant: { admin: 1, maintainer: 1, reviewer: 1, viewer: 1 } },
      { action: "Take / release task ownership", grant: { admin: 1, maintainer: 1, reviewer: 1, viewer: 1 } },
      { action: "Release any task owner", grant: { admin: 1, maintainer: 0, reviewer: 0, viewer: 0 } },
      { action: "Approve stage transitions", grant: { admin: 1, maintainer: 1, reviewer: 0, viewer: 0 } },
      { action: "Accept completion → Done", grant: { admin: 1, maintainer: 1, reviewer: 0, viewer: 0 } },
      { action: "Open agent runtime sessions", grant: { admin: 1, maintainer: 1, reviewer: 0, viewer: 0 } },
      { action: "Manage members & roles", grant: { admin: 1, maintainer: 0, reviewer: 0, viewer: 0 } },
      { action: "Edit workflow & policy", grant: { admin: 1, maintainer: 0, reviewer: 0, viewer: 0 } },
    ],
    transitions: [
      { from: "triage", to: "ready", by: "Human, after the quality gate — agents may flag underspecified tasks", boundary: "approval" },
      { from: "ready", to: "impl", by: "Operator, when a primary specialist is assigned", boundary: "auto" },
      { from: "impl", to: "review", by: "Operator transition request, with evidence attached", boundary: "approval" },
      { from: "review", to: "done", by: "Human acceptance of the completion report", boundary: "human", locked: true },
    ],
    repo: {
      name: "akin-ozer/viberr", override: true,
      credential: "viberr-bot · fine-grained PAT", masked: "github_pat_••••42af",
      scopes: [
        { id: "repo", ok: true },
        { id: "workflow", ok: true },
        { id: "read:org", ok: true },
        { id: "pull_request:write", ok: false, task: "VIB-142" },
      ],
    },
    guardrails: [
      { id: "meaningful-comment", desc: "Agent comments must add information — status chatter is rejected before it reaches the timeline.", on: true },
      { id: "operator-brevity", desc: "Operator packets keep to observed → changed → recommended → decision required.", on: true },
      { id: "no-duplicate-summary", desc: "A summary that restates an earlier one is dropped instead of appended.", on: true },
      { id: "compression-threshold", desc: "Long timelines compress once routine events pass the threshold; typed events are always kept.", on: true, value: 40, unit: "events" },
      { id: "evidence-separation", desc: "Raw validation output stays in evidence references — never inline in the task record.", on: true },
    ],
    events: [
      { kind: "violation", t: "today 9:38", text: "Project credential is missing `pull_request:write` — flagged by the policy engine on", task: "VIB-142", open: true },
      { kind: "blockedact", t: "yesterday 16:04", text: "Blocked: Developer (Codex) attempted **Merge a pull request** — reserved for humans — on", task: "VIB-145" },
      { kind: "audit", t: "yesterday 11:20", text: "Murat opened the Developer runtime session for debugging — recorded per audit policy on", task: "VIB-160" },
      { kind: "change", t: "Mar 30", text: "Elif locked **Review → Done** to human-only acceptance." },
      { kind: "change", t: "Mar 30", text: "Human RBAC and agent capability split into separate policy surfaces —", task: "VIB-139" },
    ],
  };

  // Notifications routed to the signed-in user (Arda) per their routing preferences.
  const NOTIFICATIONS = [
    { id: "n-160-packet", kind: "packet", ptype: "blocked", unread: true, day: "Today", t: "10:31", from: { name: "Operator", kind: "agent" }, task: "VIB-160",
      title: "Blocked decision — pick a recovery path",
      text: "Provider history unavailable and two rehydrate checks failing. The specialist continues from `task.md` once you choose." },
    { id: "n-142-packet", kind: "packet", ptype: "input", unread: true, day: "Today", t: "9:41", from: { name: "Operator", kind: "agent" }, task: "VIB-142",
      title: "Completion report — waiting on your acceptance",
      text: "Workspace attach implemented, **PR #318** open, validation green. Only a human can move it to Done." },
    { id: "n-145-approval", kind: "approval", unread: true, day: "Today", t: "9:12", from: { name: "Operator", kind: "agent" }, task: "VIB-145",
      title: "Transition request — In Progress → Review",
      text: "SSE fan-out demo recorded and evidence attached. This boundary needs a maintainer approval." },
    { id: "n-142-policy", kind: "policy", unread: true, day: "Today", t: "9:38", from: { name: "Policy engine", kind: "system" }, task: "VIB-142",
      text: "**Policy violation:** the active PAT is missing `pull_request:write` — PR auto-sync will fail after merge." },
    { id: "n-142-quality", kind: "quality", unread: false, day: "Today", t: "9:20", from: claude("Reviewer"), task: "VIB-142",
      text: "**Quality flag:** snapshot `task_projection.json` changed — confirm the compact shape before review." },
    { id: "n-148-mention", kind: "mention", unread: false, day: "Today", t: "8:20", from: ELIF, task: "VIB-148",
      text: "mentioned you — “needs a reviewer to own the acceptance gate. **@arda** can you take it?”" },
    { id: "n-145-blockedact", kind: "policy", unread: false, day: "Yesterday", t: "16:04", from: { name: "Policy engine", kind: "system" }, task: "VIB-145",
      text: "Blocked agent action: Developer (Codex) attempted **Merge a pull request** — reserved for humans." },
    { id: "n-160-reply", kind: "mention", unread: false, day: "Yesterday", t: "11:20", from: MURAT, task: "VIB-160",
      text: "replied to you — “opened the Developer runtime session to debug continuity; findings come back as task comments.”" },
  ];
  // The stream is global to the user — items arrive from every project.
  NOTIFICATIONS.splice(1, 0,
    { id: "n-dep-31", kind: "packet", ptype: "input", unread: true, day: "Today", t: "10:12", from: { name: "Operator", kind: "agent" }, task: "DEP-31", project: "Deploy Pipeline",
      title: "Completion report — staging promotion ready",
      text: "Pipeline stage rework validated on a dry run. Promotion to staging needs your acceptance." });
  NOTIFICATIONS.splice(3, 0,
    { id: "n-bil-9", kind: "approval", unread: true, day: "Today", t: "8:47", from: { name: "Operator", kind: "agent" }, task: "BIL-9", project: "Billing Service",
      title: "Transition request — Ready → In Progress",
      text: "Strict human-gate project: execution can't start without a maintainer approval." });
  NOTIFICATIONS.forEach((n) => { if (!n.project) n.project = "Viberr Core"; });
  // Read-state is per user and shared across surfaces (Home + workspace).
  try {
    const readIds = JSON.parse(localStorage.getItem("viberr:notifs:read") || "[]");
    NOTIFICATIONS.forEach((n) => { if (readIds.indexOf(n.id) !== -1) n.unread = false; });
  } catch (e) {}

  window.VIBERR = {
    project: { name: "Viberr Core", repo: "akin-ozer/viberr", members: 4 },
    stages: STAGES,
    tasks: TASKS,
    runtime: RUNTIME,
    people: { ARDA, ELIF, MURAT, SELIN, DENIZ },
    agents: AGENTS,
    policy: POLICY,
    notifications: NOTIFICATIONS,
    session: {
      get: function () { try { return JSON.parse(localStorage.getItem("viberr:session") || "null"); } catch (e) { return null; } },
      set: function (s) { try { localStorage.setItem("viberr:session", JSON.stringify(s)); } catch (e) {} },
      clear: function () { try { localStorage.removeItem("viberr:session"); } catch (e) {} },
    },
    markNotifsRead: function (ids) {
      try {
        const cur = JSON.parse(localStorage.getItem("viberr:notifs:read") || "[]");
        localStorage.setItem("viberr:notifs:read", JSON.stringify(Array.from(new Set(cur.concat(ids)))));
      } catch (e) {}
    },
  };
})();
