import type Database from "better-sqlite3";
import { emitProjectionEvent } from "~/server/events/projection-events.server";
import { isNotifKindEnabled } from "~/features/profile/profile-query.server";
import type { ActorRender } from "~/shared/mapping/actor.server";
import {
  mapNotificationRow,
  type NotificationKind,
  type NotificationRecord,
  type NotificationRow,
} from "~/shared/mapping/notification.server";
import { newId } from "~/shared/ids/new-id.server";

/**
 * Per-user notification rows (orchestrator ruling 9): SQLite-owned,
 * sorted by real timestamp DESC, task/project soft refs (cross-project
 * capable — the seed's DEP-31/BIL-9 rows point at the stub projects).
 * Read state is monotonic (no mark-unread) and idempotent.
 */

export interface CreateNotificationInput {
  /** Deterministic id for idempotent seeding; autogenerated when omitted. */
  id?: string;
  userId: string;
  kind: NotificationKind;
  ptype?: "input" | "blocked" | null;
  title?: string | null;
  text: string;
  from?: ActorRender | null;
  projectSlug?: string | null;
  taskKey?: string | null;
  occurredAt?: string;
  readAt?: string | null;
  /** Skip the recipient's routing-pref filter. For FIXTURE inserts (the demo
   *  seed) only — a fixture must be deterministic and not vary with whatever
   *  prefs a prior session left, or `seed --reset` stops being pristine. */
  bypassPrefs?: boolean;
}

/**
 * Insert a per-user notification — UNLESS the recipient has silenced its
 * routing category (FR26 / profile notification routing). This is the single
 * insert point every creation path funnels through (task watcher fan-out,
 * @mention, policy engine, seed), so gating here is what makes the profile
 * toggles govern real delivery instead of being decorative. Opt-out model: a
 * user with no stored pref receives everything (default ON), and a prefs-read
 * failure defaults to delivering — a routing lookup must never silently drop a
 * governance notification. Returns the row id, or null when the category was
 * off and nothing was written.
 */
export function createNotification(
  db: Database.Database,
  input: CreateNotificationInput,
): string | null {
  let deliver = true;
  if (!input.bypassPrefs) {
    try {
      deliver = isNotifKindEnabled(db, input.userId, input.kind);
    } catch {
      deliver = true; // never drop a notification on a prefs-lookup error
    }
  }
  if (!deliver) return null;

  const id = input.id ?? newId("ntf");
  const now = new Date().toISOString();
  db.prepare(
    `INSERT OR REPLACE INTO notifications
       (id, user_id, kind, ptype, title, text, actor_json, project_slug,
        task_key, occurred_at, read_at, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(
    id,
    input.userId,
    input.kind,
    input.ptype ?? null,
    input.title ?? null,
    input.text,
    input.from ? JSON.stringify(input.from) : null,
    input.projectSlug ?? null,
    input.taskKey ?? null,
    input.occurredAt ?? now,
    input.readAt ?? null,
    now,
  );
  emitProjectionEvent({
    type: "notification.created",
    userId: input.userId,
    occurredAt: input.occurredAt ?? now,
  });
  return id;
}

/** Newest-first by real timestamp (deliberate divergence from the mock's
 * splice order — ruling 9). Joins project display names where resolvable. */
export function listNotifications(
  db: Database.Database,
  userId: string,
  options: { limit?: number } = {},
): NotificationRecord[] {
  const rows = db
    .prepare(
      `SELECT n.*, p.name AS project_name
       FROM notifications n
       LEFT JOIN projects p ON p.slug = n.project_slug
       WHERE n.user_id = ?
       ORDER BY n.occurred_at DESC, n.id DESC
       LIMIT ?`,
    )
    .all(userId, options.limit ?? 100) as NotificationRow[];
  return rows.map(mapNotificationRow);
}

export function countUnreadNotifications(
  db: Database.Database,
  userId: string,
): number {
  const row = db
    .prepare(
      `SELECT count(*) AS c FROM notifications WHERE user_id = ? AND read_at IS NULL`,
    )
    .get(userId) as { c: number };
  return row.c;
}

/** Idempotent read-marking (monotonic; re-marking is a no-op). */
export function markNotificationsRead(
  db: Database.Database,
  userId: string,
  ids: string[],
): number {
  if (ids.length === 0) return 0;
  const placeholders = ids.map(() => "?").join(", ");
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE user_id = ? AND read_at IS NULL AND id IN (${placeholders})`,
    )
    .run(new Date().toISOString(), userId, ...ids);
  return result.changes;
}

export function markAllNotificationsRead(
  db: Database.Database,
  userId: string,
): number {
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ? WHERE user_id = ? AND read_at IS NULL`,
    )
    .run(new Date().toISOString(), userId);
  return result.changes;
}

/**
 * Packet/approval resolution side-effect (contracts §1.2): marks that
 * task's packet + approval notifications read for EVERY user, idempotently.
 */
export function markTaskPacketApprovalRead(
  db: Database.Database,
  projectSlug: string,
  taskKey: string,
  kinds: NotificationKind[] = ["packet", "approval"],
): number {
  if (kinds.length === 0) return 0;
  const placeholders = kinds.map(() => "?").join(", ");
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE project_slug = ? AND task_key = ? AND read_at IS NULL
         AND kind IN (${placeholders})`,
    )
    .run(new Date().toISOString(), projectSlug, taskKey, ...kinds);
  return result.changes;
}
