import type { DatabaseSync } from "node:sqlite";
import { emitProjectionEvent } from "~/server/events/projection-events.server";
import { isNotifKindEnabled } from "~/features/profile/profile-query.server";
import {
  createActorRenderOverlay,
  type ActorRender,
} from "~/shared/mapping/actor.server";
import {
  DECISION_NOTIFICATION_KINDS,
  isDecisionKind,
  mapNotificationRow,
  type NotificationKind,
  type NotificationRecord,
  type NotificationRow,
} from "~/shared/mapping/notification.server";
import { newId } from "~/shared/ids/new-id.server";
import { plainText } from "~/features/notifications/notification-meta";
import type { AttentionSnapshot } from "~/features/notifications/desktop-alerts";
import { isDocumentNavigation } from "~/server/http/single-fetch.server";
import { decisionsRequiring } from "~/server/projections/decisions.server";
import {
  decisionAnchor,
  proposalAnchor,
  TASK_DECISION_ANCHOR,
  TASK_RECOMMENDATIONS_ANCHOR,
  timelineEventAnchor,
} from "~/shared/page-anchors";
import { epicHref } from "~/shared/epic-href";

/**
 * Per-user notification rows (orchestrator ruling 9): SQLite-owned,
 * sorted by real timestamp DESC, task/project soft refs (cross-project
 * capable — the seed's DEP-31/BIL-9 rows point at the stub projects).
 * Read state is monotonic (no mark-unread) and idempotent.
 */

export interface CreateNotificationInput {
  /** Deterministic id for idempotent seeding; autogenerated when omitted. */
  id?: string;
  userId: string;
  kind: NotificationKind;
  ptype?: "input" | "blocked" | null;
  title?: string | null;
  text: string;
  from?: ActorRender | null;
  projectSlug?: string | null;
  taskKey?: string | null;
  /** Ruling 497: where the row opens, when the notifier knows the exact thing
   *  it is about (the link builders below). Omitted, it opens the task, or the
   *  project's board (`notificationHref`). */
  href?: string | null;
  occurredAt?: string;
  readAt?: string | null;
  /** Skip the recipient's routing-pref filter. For FIXTURE inserts (the demo
   *  seed) only — a fixture must be deterministic and not vary with whatever
   *  prefs a prior session left, or `seed --reset` stops being pristine. */
  bypassPrefs?: boolean;
}

/**
 * Insert a per-user notification — UNLESS the recipient has silenced its
 * routing category (FR26 / profile notification routing). This is the single
 * insert point every creation path funnels through (task watcher fan-out,
 * @mention, policy engine, seed), so gating here is what makes the profile
 * toggles govern real delivery instead of being decorative. Opt-out model: a
 * user with no stored pref receives everything (default ON), and a prefs-read
 * failure defaults to delivering — a routing lookup must never silently drop a
 * governance notification. Returns the row id, or null when the category was
 * off and nothing was written.
 */
export function createNotification(
  db: DatabaseSync,
  input: CreateNotificationInput,
): string | null {
  let deliver = true;
  if (!input.bypassPrefs) {
    try {
      deliver = isNotifKindEnabled(db, input.userId, input.kind);
    } catch {
      deliver = true; // never drop a notification on a prefs-lookup error
    }
  }
  if (!deliver) return null;

  const id = input.id ?? newId("ntf");
  const now = new Date().toISOString();
  db.prepare(
    `INSERT OR REPLACE INTO notifications
       (id, user_id, kind, ptype, title, text, actor_json, project_slug,
        task_key, href, occurred_at, read_at, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(
    id,
    input.userId,
    input.kind,
    input.ptype ?? null,
    input.title ?? null,
    input.text,
    input.from ? JSON.stringify(input.from) : null,
    input.projectSlug ?? null,
    input.taskKey ?? null,
    input.href ?? null,
    input.occurredAt ?? now,
    input.readAt ?? null,
    now,
  );
  emitProjectionEvent({
    type: "notification.created",
    userId: input.userId,
    occurredAt: input.occurredAt ?? now,
  });
  return id;
}

function projectPath(projectSlug: string): string {
  return `/projects/${projectSlug}`;
}

function taskPath(projectSlug: string, taskKey: string): string {
  return `${projectPath(projectSlug)}/tasks/${taskKey}`;
}

/**
 * Ruling 497: the links a notifier records (`CreateNotificationInput.href`), one
 * per thing a row can be about. Each opens inside the row's own project, which
 * `notificationHref` checks.
 */

/** An event on the task's timeline: the page scrolls to it and marks it. */
export function taskEventLink(projectSlug: string, taskKey: string, occurredAt: string): string {
  return `${taskPath(projectSlug, taskKey)}#${timelineEventAnchor(occurredAt)}`;
}

/** The task's open decision packet (an operator's, or an agent's question).
 *  Ruling 547: named by its id, so {@link followClosedDecision} can find the
 *  rows about it; a packet with no id (written before F10-09) is not. */
export function taskDecisionLink(
  projectSlug: string,
  taskKey: string,
  packetId?: string,
): string {
  const anchor = packetId ? decisionAnchor(packetId) : TASK_DECISION_ANCHOR;
  return `${taskPath(projectSlug, taskKey)}#${anchor}`;
}

/** Ruling 547: a decision packet that closed, and the timeline event that
 *  recorded how (the answer, the withdrawal, the fulfilled goal edit, or the
 *  acceptance or archive it ended with). */
export interface ClosedDecision {
  /** The packet's id; a packet with none has no rows to follow it. */
  packetId: string | undefined;
  /** The `occurredAt` of the event that recorded the close. */
  closedAt: string;
}

/**
 * Ruling 547: the rows that opened a decision packet open the event that
 * closed it, once it has. Their link named the packet (`taskDecisionLink`),
 * and the task page shows a packet only while it is open, so a click on a row
 * about a question already answered used to move nothing at all. The rows keep
 * their read state; the callers that mark them read still do.
 */
export function followClosedDecision(
  db: DatabaseSync,
  projectSlug: string,
  taskKey: string,
  closed: ClosedDecision,
): number {
  if (!closed.packetId) return 0;
  return Number(
    db
      .prepare(
        `UPDATE notifications SET href = ?
         WHERE project_slug = ? AND task_key = ? AND href = ?`,
      )
      .run(
        taskEventLink(projectSlug, taskKey, closed.closedAt),
        projectSlug,
        taskKey,
        taskDecisionLink(projectSlug, taskKey, closed.packetId),
      ).changes,
  );
}

/** The task's pending recommendations, each a decision to apply. */
export function taskRecommendationsLink(projectSlug: string, taskKey: string): string {
  return `${taskPath(projectSlug, taskKey)}#${TASK_RECOMMENDATIONS_ANCHOR}`;
}

/** A knowledge-base proposal's entry on the project Controller page, where it
 *  is promoted or dismissed (ruling 483). */
export function proposalLink(projectSlug: string, proposalId: string): string {
  return `${projectPath(projectSlug)}/controller#${proposalAnchor(proposalId)}`;
}

/** The project's GitHub page: its connection, credential and pull requests. */
export function projectGithubLink(projectSlug: string): string {
  return `${projectPath(projectSlug)}/github`;
}

/** An epic's own page (ruling 503). */
export function epicLink(projectSlug: string, epicId: string): string {
  return epicHref(projectSlug, epicId);
}

/**
 * B-FD6: where a notification row actually goes when clicked. The inbox routed
 * only rows carrying BOTH a project and a task, so an org- or project-level row
 * (a policy notification, a project-scoped quality alert) rendered exactly like
 * a clickable one and did nothing — a dead click with no explanation. Resolving
 * the destination here, once, lets every surface either navigate or render the
 * row as plainly non-clickable instead of each one re-deriving the rule.
 *
 * Ruling 497: a row that recorded where it opens opens there. That link must
 * stay inside the project the row names, so the orphan rule (F18-1) and a
 * member's removal (`deleteMemberProjectNotifications`) cover it too; one that
 * does not is ignored for the task or board the row names.
 */
function notificationHref(
  record: Pick<NotificationRecord, "projectSlug" | "taskKey"> & { href: string | null },
): string | null {
  // Org-wide rows (no project ref) concern no single page — never clickable.
  if (!record.projectSlug) return null;
  const project = projectPath(record.projectSlug);
  if (record.href && opensInside(record.href, project)) return record.href;
  if (record.taskKey) return taskPath(record.projectSlug, record.taskKey);
  // A project-scoped row still has a surface it concerns: that project's board.
  return project;
}

/** `href` is the project's own page or somewhere under it. */
function opensInside(href: string, project: string): boolean {
  if (!href.startsWith(project)) return false;
  const rest = href.slice(project.length);
  return rest === "" || rest.startsWith("/") || rest.startsWith("#") || rest.startsWith("?");
}

export interface NotificationListItem extends NotificationRecord {
  /** Resolved destination, or null when this row concerns no navigable
   *  surface — the signal a renderer uses to style it as non-clickable. */
  href: string | null;
  /**
   * F18-1: the row names a project (projectSlug set) that no longer exists in
   * the store — e.g. the project was deleted after the notification was written.
   * Its `href` is nulled (clicking it 404'd on a shell-less error page), the
   * renderer shows a "no longer exists" note, and it is dropped from the unread
   * badge (`countUnreadNotifications`) so a wiped project stops inflating it.
   */
  targetMissing: boolean;
}

/**
 * E6: ONE reading of "waiting on you", shared by the two surfaces that answer
 * that question — this inbox and Home's project cards. They each used to pick
 * their own bucket out of `decisionsRequiring`, which is a comment-deep
 * agreement: nothing failed if one of them started counting the other bucket.
 *
 * The reading: a decision waits on YOU iff it is in `mine`. The org-admin
 * `overrideEligible` bucket is deliberately NOT folded in — the D2 override is
 * governance reach into a project the admin holds no acting role in, not a
 * personal to-do, and folding it in would tell an org admin they personally owe
 * an answer on every project in the instance. It is not dropped either: Home
 * carries it as its own `overrideWaiting` counter, under its own label, so the
 * reach stays visible without inflating the inbox number. The notifications
 * list has no second counter because it has no row to hang one on — a
 * notification exists only for someone who was actually notified.
 */
export interface DecisionInboxIndex {
  /** `${projectSlug}::${taskKey}` for every decision waiting on this user. */
  waitingOnYou: Set<string>;
  /** projectSlug → how many decisions wait on this user there. */
  waitingBySlug: Map<string, number>;
  /** projectSlug → how many are reachable ONLY through the org-admin override. */
  overrideBySlug: Map<string, number>;
}

export function indexDecisionInbox(
  db: DatabaseSync,
  userId: string,
): DecisionInboxIndex {
  const decisions = decisionsRequiring(db, userId);
  const waitingOnYou = new Set<string>();
  const waitingBySlug = new Map<string, number>();
  for (const d of decisions.mine) {
    waitingOnYou.add(`${d.projectSlug}::${d.taskKey}`);
    waitingBySlug.set(d.projectSlug, (waitingBySlug.get(d.projectSlug) ?? 0) + 1);
  }
  const overrideBySlug = new Map<string, number>();
  for (const d of decisions.overrideEligible) {
    overrideBySlug.set(
      d.projectSlug,
      (overrideBySlug.get(d.projectSlug) ?? 0) + 1,
    );
  }
  return { waitingOnYou, waitingBySlug, overrideBySlug };
}

/** Newest-first by real timestamp (deliberate divergence from the mock's
 * splice order — ruling 9). Joins project display names where resolvable,
 * plus the LIVE task decision state (F7-NOTIF1): packet/approval rows are
 * reconciled against task_projections at read time — same-database join,
 * no per-mutation notification writes — so `waitingOnYou` reflects whether
 * the decision is actually still open. Home's per-project decision counts
 * come from `indexDecisionInbox` below, so the two cannot disagree. */
export function listNotifications(
  db: DatabaseSync,
  userId: string,
  options: { limit?: number } = {},
): NotificationListItem[] {
  // SAFETY: `n.*` is the `notifications` table, whose columns are
  // NotificationRow's required fields one-for-one with the same nullability
  // (`kind` pinned by its CHECK constraint to NOTIFICATION_KINDS, `ptype` to
  // input|blocked). The five joined columns are exactly NotificationRow's
  // OPTIONAL fields, which the LEFT JOINs leave null when unmatched.
  const rows = db
    .prepare(
      `SELECT n.*, p.name AS project_name, p.stages_json AS project_stages_json,
              t.stage AS task_stage,
              (t.packet_json IS NOT NULL AND t.packet_json <> '') AS task_has_packet,
              t.recommendation_count AS task_recommendation_count
       FROM notifications n
       LEFT JOIN projects p ON p.slug = n.project_slug
       LEFT JOIN task_projections t
         ON t.project_slug = n.project_slug AND t.task_key = n.task_key
       WHERE n.user_id = ?
       ORDER BY n.occurred_at DESC, n.rowid DESC
       LIMIT ?`,
    )
    .all(userId, options.limit ?? 100) as NotificationRow[];
  // E1: `from` actors are baked at creation — overlay the current
  // users-table identity so renames reflect in the inbox immediately.
  const overlay = createActorRenderOverlay(db);
  // R8-3: "Waiting on you" is member-scoped — a decision notification waits on
  // THIS user only if its task is in the user's actionable decision set
  // (maintainer+ / task-owner, and NOT the org-admin override). This subsumes
  // the old live-decision check AND drops decisions the viewer can't act on
  // (non-member inflation) and superseded packets (the set keys off live task
  // state, one decision per task). E6: the bucket choice is `indexDecisionInbox`
  // above, which Home reads too — not a local pick out of `decisionsRequiring`.
  const { waitingOnYou: mine } = indexDecisionInbox(db, userId);
  return rows.map((row) => {
    const record = mapNotificationRow(row);
    // F18-1: the LEFT JOIN yields a null project name only when no projects row
    // matches the slug — i.e. the project this row points at is gone. Such a row
    // has no live surface to open (its board/task 404s), so it is not clickable
    // and the renderer flags it as orphaned. (A null project_slug is an org-wide
    // row, not an orphan.)
    const targetMissing = record.projectSlug != null && row.project_name == null;
    const scoped: NotificationListItem = {
      ...record,
      waitingOnYou:
        isDecisionKind(record.kind) &&
        record.projectSlug != null &&
        record.taskKey != null &&
        mine.has(`${record.projectSlug}::${record.taskKey}`),
      href: targetMissing ? null : notificationHref({ ...record, href: row.href }),
      targetMissing,
    };
    return scoped.from ? { ...scoped, from: overlay(scoped.from) } : scoped;
  });
}

/**
 * Drop every notification that pointed into a project (C01-A12, pass 32 —
 * the project-delete action used to run this DELETE inline, the one write to
 * this table outside the module that owns it). Notifications are app-owned
 * (no FK cascade to projects), so a deleted project would otherwise leave
 * orphaned "waiting on you" rows that dead-end on a 404 when opened (F2).
 */
export function deleteProjectNotifications(db: DatabaseSync, projectSlug: string): number {
  return Number(
    db.prepare(`DELETE FROM notifications WHERE project_slug = ?`).run(projectSlug).changes,
  );
}

/** One person's notifications for one project — what a member REMOVAL leaves
 *  behind. `deleteProjectNotifications` covers the project going away, and
 *  `countUnreadNotifications` already discounts rows whose project is gone; a
 *  removed member is the third case, and the only one where the project still
 *  EXISTS, so their rows kept rendering and kept counting while every click
 *  dead-ended on a project they can no longer reach. */
export function deleteMemberProjectNotifications(
  db: DatabaseSync,
  projectSlug: string,
  userId: string,
): number {
  return Number(
    db
      .prepare(
        `DELETE FROM notifications WHERE project_slug = ? AND user_id = ?`,
      )
      .run(projectSlug, userId).changes,
  );
}

/** What the bell draws without its list (ruling 457): the badge and the
 *  popover head. */
export interface BellCounts {
  /** The badge: unread rows that lead somewhere (see below). */
  unread: number;
  /** F19-25: unread rows whose project is gone. They are not in the badge,
   *  but the list still shows them wearing their unread dot, so the popover
   *  head counts them too (`unread + orphanUnread`) and keeps Mark all read. */
  orphanUnread: number;
}

/**
 * Ruling 457 (FL-4 / SRV-6): the bell's two counts in one statement. Pages
 * ship these instead of the bell's list, which the bell loads itself
 * (`routes/resources.notifications.ts`).
 *
 * F18-1: an unread row that points at a DELETED project is not actionable —
 * clicking it 404s — so it must not inflate the bell badge. `unread` counts
 * unread rows that are either org-wide (no project_slug) or whose project still
 * exists; `orphanUnread` counts the rest. The two are disjoint by construction.
 * F19-25 used to count the orphans among the listed rows on the client; the
 * server counts all of them, so the head no longer depends on the list's cap.
 */
export function bellCounts(db: DatabaseSync, userId: string): BellCounts {
  // SAFETY: an un-grouped aggregate always returns exactly one row; `total()`
  // is 0.0 (never NULL) over no rows, so both columns are always numbers.
  const row = db
    .prepare(
      `SELECT
         total(n.project_slug IS NULL OR p.slug IS NOT NULL) AS unread,
         total(n.project_slug IS NOT NULL AND p.slug IS NULL) AS orphan
       FROM notifications n
       LEFT JOIN projects p ON p.slug = n.project_slug
       WHERE n.user_id = ? AND n.read_at IS NULL`,
    )
    .get(userId) as { unread: number; orphan: number };
  return { unread: Number(row.unread), orphanUnread: Number(row.orphan) };
}

export function countUnreadNotifications(
  db: DatabaseSync,
  userId: string,
): number {
  return bellCounts(db, userId).unread;
}

/** How many of the newest unread decisions a snapshot carries. A tab reads it
 *  about once a minute at most, so more than this arriving between two reads
 *  is a burst the bell and the title count still show. */
export const ATTENTION_ITEM_CAP = 10;

/** A desktop notification body is a line or two on every platform. */
const ATTENTION_BODY_MAX = 180;

/**
 * Ruling 481(c) (F40-51): what reaches a tab nobody is looking at. `waiting`
 * is the count of unread decision rows (`DECISION_NOTIFICATION_KINDS`: an
 * operator packet, an agent's question, a recommendation to approve) that lead
 * somewhere, under the bell's own orphan rule (F18-1), and it is the number
 * the tab's title carries. `items` are the newest of those rows, already
 * worded for a desktop notification (`attention-watcher.tsx`, opt-in on
 * Profile), each with the destination the bell would open.
 */
export function attentionSnapshot(db: DatabaseSync, userId: string): AttentionSnapshot {
  const kinds = DECISION_NOTIFICATION_KINDS.map(() => "?").join(", ");
  const live = `n.user_id = ? AND n.read_at IS NULL AND n.kind IN (${kinds})
                AND (n.project_slug IS NULL OR p.slug IS NOT NULL)`;
  // SAFETY: an un-grouped aggregate always returns exactly one row, and
  // `count(*)` is never NULL.
  const counted = db
    .prepare(
      `SELECT count(*) AS c FROM notifications n
       LEFT JOIN projects p ON p.slug = n.project_slug
       WHERE ${live}`,
    )
    .get(userId, ...DECISION_NOTIFICATION_KINDS) as { c: number };
  // SAFETY: `n.*` columns as `NotificationRow` declares them (the same table
  // `listNotifications` reads), plus the joined project name, which the LEFT
  // JOIN leaves null for an org-wide row.
  const rows = db
    .prepare(
      `SELECT n.id, n.kind, n.title, n.text, n.project_slug, n.task_key, n.href,
              p.name AS project_name
       FROM notifications n
       LEFT JOIN projects p ON p.slug = n.project_slug
       WHERE ${live}
       ORDER BY n.occurred_at DESC, n.rowid DESC
       LIMIT ?`,
    )
    .all(userId, ...DECISION_NOTIFICATION_KINDS, ATTENTION_ITEM_CAP) as Array<
    Pick<
      NotificationRow,
      "id" | "kind" | "title" | "text" | "project_slug" | "task_key" | "href"
    > & {
      project_name: string | null;
    }
  >;
  return {
    waiting: Number(counted.c),
    items: rows.map((row) => {
      const where = [row.task_key, row.project_name].filter(Boolean).join(" · ");
      const text = plainText(row.text).replace(/\s+/g, " ").trim();
      const body = where ? `${where}\n${text}` : text;
      return {
        id: row.id,
        title: row.title ?? "A decision waits on you",
        body: body.length > ATTENTION_BODY_MAX ? `${body.slice(0, ATTENTION_BODY_MAX - 1)}…` : body,
        href: notificationHref({
          projectSlug: row.project_slug,
          taskKey: row.task_key,
          href: row.href,
        }),
      };
    }),
  };
}

/** Targeted `notification.read` — other tabs of the same user revalidate so
 * their bell badge drops (E12: mark-read used to emit nothing). */
function emitNotificationRead(userId: string): void {
  emitProjectionEvent({
    type: "notification.read",
    userId,
    occurredAt: new Date().toISOString(),
  });
}

/** Idempotent read-marking (monotonic; re-marking is a no-op). */
export function markNotificationsRead(
  db: DatabaseSync,
  userId: string,
  ids: string[],
): number {
  if (ids.length === 0) return 0;
  const placeholders = ids.map(() => "?").join(", ");
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE user_id = ? AND read_at IS NULL AND id IN (${placeholders})`,
    )
    .run(new Date().toISOString(), userId, ...ids);
  const changes = Number(result.changes);
  if (changes > 0) emitNotificationRead(userId);
  return changes;
}

export function markAllNotificationsRead(
  db: DatabaseSync,
  userId: string,
): number {
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ? WHERE user_id = ? AND read_at IS NULL`,
    )
    .run(new Date().toISOString(), userId);
  const changes = Number(result.changes);
  if (changes > 0) emitNotificationRead(userId);
  return changes;
}

/**
 * Packet/approval resolution side-effect (contracts §1.2): marks that
 * task's decision notifications (packet, question, approval) read for EVERY
 * user, idempotently. Emits `notification.read` per affected user (their
 * badges drop live). Ruling 481(a): an agent's question is a packet on the
 * task, so resolving the packet clears its `question` row too.
 */
export function markTaskPacketApprovalRead(
  db: DatabaseSync,
  projectSlug: string,
  taskKey: string,
  kinds: readonly NotificationKind[] = DECISION_NOTIFICATION_KINDS,
): number {
  if (kinds.length === 0) return 0;
  const placeholders = kinds.map(() => "?").join(", ");
  // Affected users FIRST (the bulk UPDATE loses them) — one event each.
  // SAFETY: the single selected column is `notifications.user_id`, TEXT NOT
  // NULL (0001_baseline.sql).
  const affected = db
    .prepare(
      `SELECT DISTINCT user_id FROM notifications
       WHERE project_slug = ? AND task_key = ? AND read_at IS NULL
         AND kind IN (${placeholders})`,
    )
    .all(projectSlug, taskKey, ...kinds) as { user_id: string }[];
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE project_slug = ? AND task_key = ? AND read_at IS NULL
         AND kind IN (${placeholders})`,
    )
    .run(new Date().toISOString(), projectSlug, taskKey, ...kinds);
  const changes = Number(result.changes);
  if (changes > 0) {
    for (const row of affected) emitNotificationRead(row.user_id);
  }
  return changes;
}

/**
 * F20-11: is this request a GENUINE top-level view of the task page — the one
 * moment R19-15's "opening the task IS seeing its notifications" actually holds
 * — as opposed to a background revalidation?
 *
 * The R19-15 loader used to mark-seen on EVERY run, justified by "this loader
 * runs only on a real view". That premise was wrong: React Router 8 single
 * fetch addresses every client-side data load to the `.data` wire URL
 * (`/projects/<slug>/tasks/<key>.data?_routes=…`) — the SSE revalidation that
 * fires on every task change, the revalidation after a POST on this page, and a
 * client-side link navigation, ALL of them. So a task parked in a background
 * tab silently consumed any notification that arrived for it within
 * milliseconds, and the bell never badged (it swallowed four "Blocked —
 * decision needed" packets in the live repro).
 *
 * Only a real top-level document load (typing the URL, a hard refresh,
 * open-in-new-tab) arrives on the clean route path — never the `.data` wire
 * address — and the browser stamps it `Sec-Fetch-Mode: navigate`. So the rule
 * is: mark-seen iff the path is NOT the single-fetch `.data` address (the same
 * framework signal `require-user.server.ts` keys off) and, when the browser
 * sends `Sec-Fetch-Mode`, it says `navigate`.
 *
 * We deliberately do NOT mark on a client-side `.data` navigation: server-side
 * it is indistinguishable from the background revalidation that caused F20-11,
 * and erring toward an un-cleared bell (it over-counts a task you are looking
 * at) is the SAFE direction — the old code erred toward silently eating an
 * unseen governance packet. The bell popover already marks a row read on click
 * (`top-bell.tsx`), so opening a task FROM a notification still clears it, and a
 * full load / "Mark all read" clears the rest.
 */
export function isTaskViewNavigation(request: Request): boolean {
  return isDocumentNavigation(request);
}

/**
 * R19-15: per-user VIEW side-effect — opening a task's page marks THIS
 * viewer's unread notifications for that (project, task) read, EVERY kind.
 * This is what lets the bell badge count genuinely-unseen items: a user who
 * reaches the task from the board (never touching the popover or the inbox)
 * must not keep its rows unread forever. Deliberately unlike
 * `markTaskPacketApprovalRead` above, which is a RESOLUTION side-effect:
 * resolving a decision clears the packet/approval kinds for EVERY user
 * because the decision itself is gone, while a view proves only that ONE
 * user has seen — so this touches one user's rows and leaves everyone
 * else's unread. Same monotonic/idempotent contract, same single
 * `notification.read` emit only when something actually changed.
 */
export function markTaskNotificationsSeen(
  db: DatabaseSync,
  userId: string,
  projectSlug: string,
  taskKey: string,
): number {
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE user_id = ? AND project_slug = ? AND task_key = ?
         AND read_at IS NULL`,
    )
    .run(new Date().toISOString(), userId, projectSlug, taskKey);
  const changes = Number(result.changes);
  if (changes > 0) emitNotificationRead(userId);
  return changes;
}
