import type Database from "better-sqlite3";
import { emitProjectionEvent } from "~/server/events/projection-events.server";
import { isNotifKindEnabled } from "~/features/profile/profile-query.server";
import {
  createActorRenderOverlay,
  type ActorRender,
} from "~/shared/mapping/actor.server";
import {
  mapNotificationRow,
  type NotificationKind,
  type NotificationRecord,
  type NotificationRow,
} from "~/shared/mapping/notification.server";
import { newId } from "~/shared/ids/new-id.server";

/**
 * Per-user notification rows (orchestrator ruling 9): SQLite-owned,
 * sorted by real timestamp DESC, task/project soft refs (cross-project
 * capable — the seed's DEP-31/BIL-9 rows point at the stub projects).
 * Read state is monotonic (no mark-unread) and idempotent.
 */

export interface CreateNotificationInput {
  /** Deterministic id for idempotent seeding; autogenerated when omitted. */
  id?: string;
  userId: string;
  kind: NotificationKind;
  ptype?: "input" | "blocked" | null;
  title?: string | null;
  text: string;
  from?: ActorRender | null;
  projectSlug?: string | null;
  taskKey?: string | null;
  occurredAt?: string;
  readAt?: string | null;
  /** Skip the recipient's routing-pref filter. For FIXTURE inserts (the demo
   *  seed) only — a fixture must be deterministic and not vary with whatever
   *  prefs a prior session left, or `seed --reset` stops being pristine. */
  bypassPrefs?: boolean;
}

/**
 * Insert a per-user notification — UNLESS the recipient has silenced its
 * routing category (FR26 / profile notification routing). This is the single
 * insert point every creation path funnels through (task watcher fan-out,
 * @mention, policy engine, seed), so gating here is what makes the profile
 * toggles govern real delivery instead of being decorative. Opt-out model: a
 * user with no stored pref receives everything (default ON), and a prefs-read
 * failure defaults to delivering — a routing lookup must never silently drop a
 * governance notification. Returns the row id, or null when the category was
 * off and nothing was written.
 */
export function createNotification(
  db: Database.Database,
  input: CreateNotificationInput,
): string | null {
  let deliver = true;
  if (!input.bypassPrefs) {
    try {
      deliver = isNotifKindEnabled(db, input.userId, input.kind);
    } catch {
      deliver = true; // never drop a notification on a prefs-lookup error
    }
  }
  if (!deliver) return null;

  const id = input.id ?? newId("ntf");
  const now = new Date().toISOString();
  db.prepare(
    `INSERT OR REPLACE INTO notifications
       (id, user_id, kind, ptype, title, text, actor_json, project_slug,
        task_key, occurred_at, read_at, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  ).run(
    id,
    input.userId,
    input.kind,
    input.ptype ?? null,
    input.title ?? null,
    input.text,
    input.from ? JSON.stringify(input.from) : null,
    input.projectSlug ?? null,
    input.taskKey ?? null,
    input.occurredAt ?? now,
    input.readAt ?? null,
    now,
  );
  emitProjectionEvent({
    type: "notification.created",
    userId: input.userId,
    occurredAt: input.occurredAt ?? now,
  });
  return id;
}

/** Newest-first by real timestamp (deliberate divergence from the mock's
 * splice order — ruling 9). Joins project display names where resolvable,
 * plus the LIVE task decision state (F7-NOTIF1): packet/approval rows are
 * reconciled against task_projections at read time — same-database join,
 * no per-mutation notification writes — so `waitingOnYou` reflects whether
 * the decision is actually still open. Home's per-project decisions counter
 * (home-query.server.ts) applies the same open-packet/pending-rec +
 * non-terminal-stage rule; keep them in step. */
export function listNotifications(
  db: Database.Database,
  userId: string,
  options: { limit?: number } = {},
): NotificationRecord[] {
  const rows = db
    .prepare(
      `SELECT n.*, p.name AS project_name, p.stages_json AS project_stages_json,
              t.stage AS task_stage,
              (t.packet_json IS NOT NULL AND t.packet_json <> '') AS task_has_packet,
              t.recommendation_count AS task_recommendation_count
       FROM notifications n
       LEFT JOIN projects p ON p.slug = n.project_slug
       LEFT JOIN task_projections t
         ON t.project_slug = n.project_slug AND t.task_key = n.task_key
       WHERE n.user_id = ?
       ORDER BY n.occurred_at DESC, n.id DESC
       LIMIT ?`,
    )
    .all(userId, options.limit ?? 100) as NotificationRow[];
  // E1: `from` actors are baked at creation — overlay the current
  // users-table identity so renames reflect in the inbox immediately.
  const overlay = createActorRenderOverlay(db);
  return rows.map((row) => {
    const record = mapNotificationRow(row);
    return record.from ? { ...record, from: overlay(record.from) } : record;
  });
}

export function countUnreadNotifications(
  db: Database.Database,
  userId: string,
): number {
  const row = db
    .prepare(
      `SELECT count(*) AS c FROM notifications WHERE user_id = ? AND read_at IS NULL`,
    )
    .get(userId) as { c: number };
  return row.c;
}

/** Targeted `notification.read` — other tabs of the same user revalidate so
 * their bell badge drops (E12: mark-read used to emit nothing). */
function emitNotificationRead(userId: string): void {
  emitProjectionEvent({
    type: "notification.read",
    userId,
    occurredAt: new Date().toISOString(),
  });
}

/** Idempotent read-marking (monotonic; re-marking is a no-op). */
export function markNotificationsRead(
  db: Database.Database,
  userId: string,
  ids: string[],
): number {
  if (ids.length === 0) return 0;
  const placeholders = ids.map(() => "?").join(", ");
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE user_id = ? AND read_at IS NULL AND id IN (${placeholders})`,
    )
    .run(new Date().toISOString(), userId, ...ids);
  if (result.changes > 0) emitNotificationRead(userId);
  return result.changes;
}

export function markAllNotificationsRead(
  db: Database.Database,
  userId: string,
): number {
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ? WHERE user_id = ? AND read_at IS NULL`,
    )
    .run(new Date().toISOString(), userId);
  if (result.changes > 0) emitNotificationRead(userId);
  return result.changes;
}

/**
 * Packet/approval resolution side-effect (contracts §1.2): marks that
 * task's packet + approval notifications read for EVERY user, idempotently.
 * Emits `notification.read` per affected user (their badges drop live).
 */
export function markTaskPacketApprovalRead(
  db: Database.Database,
  projectSlug: string,
  taskKey: string,
  kinds: NotificationKind[] = ["packet", "approval"],
): number {
  if (kinds.length === 0) return 0;
  const placeholders = kinds.map(() => "?").join(", ");
  // Affected users FIRST (the bulk UPDATE loses them) — one event each.
  const affected = db
    .prepare(
      `SELECT DISTINCT user_id FROM notifications
       WHERE project_slug = ? AND task_key = ? AND read_at IS NULL
         AND kind IN (${placeholders})`,
    )
    .all(projectSlug, taskKey, ...kinds) as { user_id: string }[];
  const result = db
    .prepare(
      `UPDATE notifications SET read_at = ?
       WHERE project_slug = ? AND task_key = ? AND read_at IS NULL
         AND kind IN (${placeholders})`,
    )
    .run(new Date().toISOString(), projectSlug, taskKey, ...kinds);
  if (result.changes > 0) {
    for (const row of affected) emitNotificationRead(row.user_id);
  }
  return result.changes;
}
