/**
 * Generates db/migrations/0013_better_auth.sql from better-auth's OWN migration
 * engine, so the DDL we ship is exactly the schema better-auth queries against.
 *
 * The schema is a function of the schema-affecting options only — the plugin
 * set (organization), email+password enabled (adds account.password), and any
 * additionalFields (none: the legacy `users` table stays canonical for
 * profile/role). Password hash/verify hooks, cookie prefix, session TTL and
 * social providers do NOT affect the schema, so this script builds a minimal
 * inline options object with no app imports (tsx can't resolve the ~ alias).
 *
 * Usage: npx tsx scripts/gen-better-auth-schema.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import { betterAuth } from "better-auth";
import { organization } from "better-auth/plugins";
import { getMigrations } from "better-auth/db/migration";

async function main(): Promise<void> {
  const db = new Database(":memory:");
  const { compileMigrations, toBeCreated } = await getMigrations({
    appName: "Viberr",
    database: db,
    secret: "gen-only-secret-at-least-32-characters-long",
    baseURL: "http://localhost:5173",
    emailAndPassword: { enabled: true },
    // Keep in sync with buildAuthOptions in app/lib/auth.server.ts — the only
    // schema-affecting extras are the org plugin and this additional field
    // (captures the GitHub login from the OAuth profile so the whitelist hook
    // can mirror it to legacy users.github_handle).
    user: {
      additionalFields: {
        githubHandle: { type: "string", required: false, input: false },
      },
    },
    plugins: [organization({ allowUserToCreateOrganization: false })],
  });
  const compiled = await compileMigrations();

  const header = `-- 0013_better_auth.sql
-- better-auth core + organization-plugin schema (generated by
-- scripts/gen-better-auth-schema.ts from better-auth's own migration engine —
-- do not hand-edit; regenerate on a better-auth bump). Coexists with the legacy
-- \`users\`/\`sessions\` tables: better-auth owns credentials + sessions + oauth +
-- org membership, bridged by  user.id === users.id.  No BEGIN/COMMIT — the
-- migration runner wraps each file in its own transaction.

`;

  // Kysely emits statements without a trailing semicolon boundary the runner
  // needs; compileMigrations already returns semicolon-terminated statements.
  const body = compiled.trim();
  const out = `${header}${body}\n`;

  const target = path.resolve(process.cwd(), "db/migrations/0013_better_auth.sql");
  writeFileSync(target, out, "utf8");

  // eslint-disable-next-line no-console
  console.log("Tables to be created:", toBeCreated.map((t) => t.table).join(", "));
  // eslint-disable-next-line no-console
  console.log(`\nWrote ${target}\n\n${out}`);
  db.close();
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error(error);
  process.exit(1);
});
